Fix mktemp call to work inside Portacle.
guicho271828/cl-sat pull request #5
Opened 2019-12-29 13:50 UTC by Kevinpgalligan

Portacle ships with BusyBox, which overrides several
common *nix commands with simpler versions, including
mktemp. This commit adds a check for Portacle and
adjusts the call to mktemp appropriately.

2019-12-29 19:43 UTC, guicho271828 commented
I believe https://stackoverflow.com/questions/2792675/how-portable-is-mktemp1 provides a rather comprehensive study.
* GNU provides `-p / --tmpdir directory`.
* Solaris supports `-p directory`
* Todd C miller's mktemp (which seems what is shipped in busybox) supports `-p  directory`
* FreeBSD (~~ OSX) has `-t prefix` but no `-p directory`
* OpenBSD has `-p directory`

So it seems `-p` is the most widely supported, except freebsd and OSX.

Two approach: (assuming the raw freebsd users are small,) it would be viable to ask OSX users to install coreutils (from brew) and we use `gmktemp` on OSX based on features.

Another is to implement the function with `-t prefix` on freebsd/osx.

2019-12-31 00:14 UTC, Kevinpgalligan commented
I'll take another look when I get the chance. I've been distracted because now that it works in Portacle, I'm unblocked from working on my own project.

2020-01-28 23:59 UTC, Kevinpgalligan commented
Hi, I'm finally free to work on this. Just a question: would you be opposed to removing the direct system calls and using CL library functions instead? All we would need is a function to create a directory, a function to create a file, and a function to generate a random string. I suspect that it might be more portable and future-proof than trying to cover all of the edge cases with specific CLI commands.

2020-01-29 01:11 UTC, guicho271828 commented
If there is a function like that then I will appreciate it

2020-01-29 03:20 UTC, guicho271828 commented
> generate a random string
well yes you can reimplement mktemp, which guarantees making a *new* temporary file with a random suffix. Such program must "check for existence, create if not exist, retry with a random name  if exist" in an atomic way (i.e. guarantee that another program creates the file after the check before the creation). `mktemp` uses `open(2)` unix system call with `O_EXCL` which guarantees this behavior. I believe `:if-exists :error` of `cl:open` has the same functionality (and is actually implemented as `open(2)` + `O_EXCL`) and therefore also atomic. There might be a similar function in uiop etc.

2020-02-02 21:00 UTC, Kevinpgalligan commented
I couldn't find an equivalent of what we wanted in uiop or other libraries, so I had to implement it from scratch. I tried to change the interface of `with-temp` as little as possible. Let me know if there are any changes we should make.

Here's the testing I did, starting from the functions at the bottom of the call chain.

```lisp
SAT> (create-nonexisting nil "/tmp/somefile")
T
SAT> (create-nonexisting nil "/tmp/somefile")
NIL
SAT> (create-nonexisting t "/tmp/somedir/")
T
SAT> (create-nonexisting t "/tmp/somedir/")
NIL
SAT> (random-base62 5)
"WtIVw"
SAT> (generate-temp-name "prefix." 5)
"prefix.fhI0C"
SAT> (attempt-create-temp nil "/tmp/" "prefix." 5 3)
"/tmp/prefix.hE8CI"
SAT> (attempt-create-temp nil "/tmp/" "gonnafailonsecondtry" 0 3)
"/tmp/gonnafailonsecondtry"
SAT> (attempt-create-temp nil "/tmp/" "gonnafailonsecondtry" 0 3)
; Evaluation aborted on #<SIMPLE-ERROR "Couldn't create a unique temp file/folder." {1002BA2A33}>.
SAT> (attempt-create-temp t "/tmp/" "a-dir" 5 3)
"/tmp/a-dirXk7td/"
SAT> (with-temp (f)
       f)
"/tmp/tmp.zPcyCos"
SAT> (with-temp (f :template "hello.XXXXX")
       f)
"/tmp/hello.CnGoJ"
SAT> (with-temp (f :debug t)
       f)
not removing /tmp/tmp.w7E4gdA for debugging
"/tmp/tmp.w7E4gdA"
SAT> (uiop:run-program "ls /tmp/ | grep tmp.w" :output '(:string :stripped t))
"tmp.w7E4gdA"
NIL
0
SAT> (uiop:run-program "ls /tmp/ | grep hello." :output '(:string :stripped t) :ignore-error-status t)
""
NIL
1
SAT> (with-temp (f :debug t :directory t)
       f)
not removing /tmp/tmp.9tsLIx0/ for debugging
"/tmp/tmp.9tsLIx0/"
SAT> (uiop:run-program "ls /tmp/ | grep tmp.9ts." :output '(:string :stripped t) :ignore-error-status t)
"tmp.9tsLIx0"
NIL
0
SAT> 
```

2020-02-08 16:12 UTC, guicho271828 requested changes

2020-02-08 16:12 UTC, guicho271828 commented on src/1-util.lisp
>             (uiop:run-program (format nil "rm -rf ~a" (namestring ,var)) :ignore-error-status t)))))
now that we are lispifying it, can we make it just use `uiop:delete-directory-tree` ?

2020-02-08 16:12 UTC, guicho271828 commented on src/1-util.lisp
> +   Signals an error if it can't generate a unique name after ATTEMPTS attempts."
As per https://github.com/coreutils/coreutils/blob/master/src/mktemp.c#L260 , can we check the minimum value for `random-string-size`?

2020-02-08 16:12 UTC, guicho271828 commented on src/1-util.lisp
> +                                   3))))
I think you can make this limit larger. Coreutils use 62^3 and therefore requires minimum three Xs in the template. https://fossies.org/dox/coreutils-8.31/tempname_8c_source.html

```
   /* A lower bound on the number of temporary files to attempt to
      generate.  The maximum total number of temporary file names that
      can exist for a given template is 62**6.  It should never be
      necessary to try all of these combinations.  Instead if a reasonable
      number of names is tried (we define reasonable as 62**3) fail to
      give the system administrator the chance to remove the problems.
      This value requires that X_SUFFIX_LEN be at least 3.  */
 #define ATTEMPTS_MIN (62 * 62 * 62)
```

2020-02-08 16:42 UTC, Kevinpgalligan commented on src/1-util.lisp
> +                                   3))))
Makes sense. How do you go about defining constants in CL? I tried it in my other project but it always resulted in warnings / errors about redefining symbols.

2020-02-08 16:43 UTC, Kevinpgalligan commented on src/1-util.lisp
> +   Signals an error if it can't generate a unique name after ATTEMPTS attempts."
👍🏻

2020-02-08 16:44 UTC, Kevinpgalligan commented
Thanks for the feedback, I should have time to work on it tomorrow.

2020-02-09 20:13 UTC, guicho271828 commented on src/1-util.lisp
> +                                   3))))
you could put them in a separate file and load the file first before use.

2020-02-26 21:32 UTC, Kevinpgalligan commented
Hi, I've addressed your comments. Here's the extra testing I've done.

```lisp
;; Enforcing minimum length of random component.
SAT> (with-temp (f :template "tmp.XX") f)
; Evaluation aborted on #<SIMPLE-ERROR "Random string part of temporary file name isn't long enough." {10042B3EC3}>.
;; Lispy file/directory deletion.
SAT> (uiop:probe-file* (with-temp (f) f))
NIL
SAT> (uiop:probe-file* (with-temp (f :debug t) f))
not removing /tmp/tmp.12gDbtx for debugging
#P"/tmp/tmp.12gDbtx"
SAT> (uiop:probe-file* (with-temp (f :directory t) f))
NIL
SAT> (uiop:probe-file* (with-temp (f :directory t :debug t) f))
not removing /tmp/tmp.UVpE0gM/ for debugging
#P"/tmp/tmp.UVpE0gM/"
```

One concern: I'm getting weird compile notes that I don't understand, not sure if it's an issue.

```
2 compiler notes:

2-class.lisp:23:3:
  note: 
    deleting unreachable code
    --> LET UNWIND-PROTECT FLET #:CLEANUP-FUN-9 BLOCK IF IF 
    --> UIOP/FILESYSTEM:DELETE-DIRECTORY-TREE MAKE-PATHNAME LIST 
    ==>
      CL-SAT::TMP
    

4-competition.lisp:70:3:
  note: 
    deleting unreachable code
    --> LET UNWIND-PROTECT FLET #:CLEANUP-FUN-62 BLOCK IF IF DELETE-FILE 
    ==>
      CL-SAT::DIR
```

2020-03-19 13:18 UTC, Kevinpgalligan commented
Hey! I hope you're keeping well, what with the COVID-19 stuff happening.

I'm sorry for dragging this out for so long, I've been really slow. Any chance of another review, though? I'm pretty sure the code is working okay, I just can't figure out how to get rid of those compiler warnings. If you have any suggestions, it would be appreciated.

2020-03-19 14:08 UTC, guicho271828 commented
ah no problem. I didn't notice the new patch, thank you!

2020-03-19 14:10 UTC, merged

2020-03-19 14:10 UTC, guicho271828 commented
I also think it is all set. Thank you for the work!

2020-03-19 14:17 UTC, Kevinpgalligan commented
Thanks for making this thing in the first place!